server:
  port: 11000
spring:
  application:
    name: fgiServer
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fgi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver_class_namel: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    max_active: 20
    initial_size: 1
    min_idle: 3
    max_wait: 60000
    time_between_eviction_runs_millis: 60000
    min_evictable_idle_time_millis: 300000
    test_while_idle: true
    test_on_borrow: false
    test_on_return: false
    poolPreparedStatements: true
debug: true
