server:

  port: 11000
spring:
  application:
    name: CRSwi_DataShield
  datasource:
    url: jdbc:mysql://39.104.52.80:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: noroot
    driver_class_namel: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    max_active: 20
    initial_size: 1
    min_idle: 3
    max_wait: 60000
    time_between_eviction_runs_millis: 60000
    min_evictable_idle_time_millis: 300000
    test_while_idle: true
    test_on_borrow: false
    test_on_return: false
    poolPreparedStatements: true
path:
    fwFilePath: /mnt/CRSwi/webfile/DataShield/FW/
    fwServerPath: http://39.108.188.95:8080/DataShield/FW/
    logFilePath: rsync@39.108.188.95::log
    logServerPath: http://39.108.188.95:8080/DataShield/log/
    localLogFilePath: /mnt/CRSwi/webfile/DataShield/log/
    logFilePwd: password
    dataFilePath: rsync@39.108.188.95::data
    dataServerPath: http://39.108.188.95:8080/DataShield/data/
    localDataFilePath: /mnt/CRSwi/webfile/DataShield/data/
    dataFilePwd: password
debug: true
