package deepthinking.fgi.dao.mapper;

import deepthinking.fgi.domain.TableAlgorithmrole;
import deepthinking.fgi.domain.TableAlgorithmroleCriteria;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TableAlgorithmroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @SelectProvider(type=TableAlgorithmroleSqlProvider.class, method="countByExample")
    long countByExample(TableAlgorithmroleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TableAlgorithmroleSqlProvider.class, method="deleteByExample")
    int deleteByExample(TableAlgorithmroleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @Delete({
        "delete from table_algorithmrole",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @Insert({
        "insert into table_algorithmrole (RoleID, AlgorithmID, ",
        "FuncID, PreAlgorithmID, ",
        "PreFuncID, Des, ",
        "Remark)",
        "values (#{roleid,jdbcType=INTEGER}, #{algorithmid,jdbcType=INTEGER}, ",
        "#{funcid,jdbcType=INTEGER}, #{prealgorithmid,jdbcType=INTEGER}, ",
        "#{prefuncid,jdbcType=INTEGER}, #{des,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TableAlgorithmrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @InsertProvider(type=TableAlgorithmroleSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(TableAlgorithmrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @SelectProvider(type=TableAlgorithmroleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="RoleID", property="roleid", jdbcType=JdbcType.INTEGER),
        @Result(column="AlgorithmID", property="algorithmid", jdbcType=JdbcType.INTEGER),
        @Result(column="FuncID", property="funcid", jdbcType=JdbcType.INTEGER),
        @Result(column="PreAlgorithmID", property="prealgorithmid", jdbcType=JdbcType.INTEGER),
        @Result(column="PreFuncID", property="prefuncid", jdbcType=JdbcType.INTEGER),
        @Result(column="Des", property="des", jdbcType=JdbcType.VARCHAR),
        @Result(column="Remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<TableAlgorithmrole> selectByExample(TableAlgorithmroleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, RoleID, AlgorithmID, FuncID, PreAlgorithmID, PreFuncID, Des, Remark",
        "from table_algorithmrole",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="RoleID", property="roleid", jdbcType=JdbcType.INTEGER),
        @Result(column="AlgorithmID", property="algorithmid", jdbcType=JdbcType.INTEGER),
        @Result(column="FuncID", property="funcid", jdbcType=JdbcType.INTEGER),
        @Result(column="PreAlgorithmID", property="prealgorithmid", jdbcType=JdbcType.INTEGER),
        @Result(column="PreFuncID", property="prefuncid", jdbcType=JdbcType.INTEGER),
        @Result(column="Des", property="des", jdbcType=JdbcType.VARCHAR),
        @Result(column="Remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    TableAlgorithmrole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableAlgorithmroleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TableAlgorithmrole record, @Param("example") TableAlgorithmroleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableAlgorithmroleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TableAlgorithmrole record, @Param("example") TableAlgorithmroleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableAlgorithmroleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TableAlgorithmrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_algorithmrole
     *
     * @mbg.generated
     */
    @Update({
        "update table_algorithmrole",
        "set RoleID = #{roleid,jdbcType=INTEGER},",
          "AlgorithmID = #{algorithmid,jdbcType=INTEGER},",
          "FuncID = #{funcid,jdbcType=INTEGER},",
          "PreAlgorithmID = #{prealgorithmid,jdbcType=INTEGER},",
          "PreFuncID = #{prefuncid,jdbcType=INTEGER},",
          "Des = #{des,jdbcType=VARCHAR},",
          "Remark = #{remark,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TableAlgorithmrole record);
}