package deepthinking.fgi.dao.mapper;

import java.util.List;
import java.util.Map;

import deepthinking.fgi.domain.TableFunc;
import deepthinking.fgi.domain.TableFuncCriteria;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TableFuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @SelectProvider(type=TableFuncSqlProvider.class, method="countByExample")
    long countByExample(TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TableFuncSqlProvider.class, method="deleteByExample")
    int deleteByExample(TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @Delete({
        "delete from table_func",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @Insert({
        "insert into table_func (ParameterName, AlgorithmID, ",
        "VarName, VarType, ",
        "ValValue, InOrOut, ",
        "Remark)",
        "values (#{parametername,jdbcType=VARCHAR}, #{algorithmid,jdbcType=INTEGER}, ",
        "#{varname,jdbcType=VARCHAR}, #{vartype,jdbcType=VARCHAR}, ",
        "#{valvalue,jdbcType=VARCHAR}, #{inorout,jdbcType=DECIMAL}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TableFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @InsertProvider(type=TableFuncSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(TableFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @SelectProvider(type=TableFuncSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ParameterName", property="parametername", jdbcType=JdbcType.VARCHAR),
        @Result(column="AlgorithmID", property="algorithmid", jdbcType=JdbcType.INTEGER),
        @Result(column="VarName", property="varname", jdbcType=JdbcType.VARCHAR),
        @Result(column="VarType", property="vartype", jdbcType=JdbcType.VARCHAR),
        @Result(column="ValValue", property="valvalue", jdbcType=JdbcType.VARCHAR),
        @Result(column="InOrOut", property="inorout", jdbcType=JdbcType.DECIMAL),
        @Result(column="Remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<TableFunc> selectByExample(TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, ParameterName, AlgorithmID, VarName, VarType, ValValue, InOrOut, Remark",
        "from table_func",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ParameterName", property="parametername", jdbcType=JdbcType.VARCHAR),
        @Result(column="AlgorithmID", property="algorithmid", jdbcType=JdbcType.INTEGER),
        @Result(column="VarName", property="varname", jdbcType=JdbcType.VARCHAR),
        @Result(column="VarType", property="vartype", jdbcType=JdbcType.VARCHAR),
        @Result(column="ValValue", property="valvalue", jdbcType=JdbcType.VARCHAR),
        @Result(column="InOrOut", property="inorout", jdbcType=JdbcType.DECIMAL),
        @Result(column="Remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    TableFunc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableFuncSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TableFunc record, @Param("example") TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableFuncSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TableFunc record, @Param("example") TableFuncCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableFuncSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TableFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_func
     *
     * @mbg.generated
     */
    @Update({
        "update table_func",
        "set ParameterName = #{parametername,jdbcType=VARCHAR},",
          "AlgorithmID = #{algorithmid,jdbcType=INTEGER},",
          "VarName = #{varname,jdbcType=VARCHAR},",
          "VarType = #{vartype,jdbcType=VARCHAR},",
          "ValValue = #{valvalue,jdbcType=VARCHAR},",
          "InOrOut = #{inorout,jdbcType=DECIMAL},",
          "Remark = #{remark,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TableFunc record);
    @Select({
                "select",
                "ID, VarName, VarType, InOrOut",
                "from table_func",
                "where AlgorithmID = #{AlgorithmID,jdbcType=INTEGER}"
        })
        @Results({
                @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
                @Result(column="VarName", property="varname", jdbcType=JdbcType.VARCHAR),
                @Result(column="VarType", property="vartype", jdbcType=JdbcType.VARCHAR),
                @Result(column="InOrOut", property="inorout", jdbcType=JdbcType.DECIMAL),
        })
        List<Map<String,Object>> selectBaseInfo(int AlgorithmID);
}