package deepthinking.fgi.dao.mapper;

import deepthinking.fgi.domain.TableModuleuserrelation;
import deepthinking.fgi.domain.TableModuleuserrelationCriteria;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface TableModuleuserrelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @SelectProvider(type=TableModuleuserrelationSqlProvider.class, method="countByExample")
    long countByExample(TableModuleuserrelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TableModuleuserrelationSqlProvider.class, method="deleteByExample")
    int deleteByExample(TableModuleuserrelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @Delete({
        "delete from table_moduleuserrelation",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @Insert({
        "insert into table_moduleuserrelation (ID, ModuleID, ",
        "UserName, Remark)",
        "values (#{id,jdbcType=INTEGER}, #{moduleid,jdbcType=INTEGER}, ",
        "#{username,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TableModuleuserrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @InsertProvider(type=TableModuleuserrelationSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(TableModuleuserrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @SelectProvider(type=TableModuleuserrelationSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ModuleID", property="moduleid", jdbcType=JdbcType.INTEGER),
        @Result(column="UserName", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="Remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<TableModuleuserrelation> selectByExample(TableModuleuserrelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, ModuleID, UserName, Remark",
        "from table_moduleuserrelation",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ModuleID", property="moduleid", jdbcType=JdbcType.INTEGER),
        @Result(column="UserName", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="Remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    TableModuleuserrelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableModuleuserrelationSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TableModuleuserrelation record, @Param("example") TableModuleuserrelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableModuleuserrelationSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TableModuleuserrelation record, @Param("example") TableModuleuserrelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TableModuleuserrelationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TableModuleuserrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_moduleuserrelation
     *
     * @mbg.generated
     */
    @Update({
        "update table_moduleuserrelation",
        "set ModuleID = #{moduleid,jdbcType=INTEGER},",
          "UserName = #{username,jdbcType=VARCHAR},",
          "Remark = #{remark,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TableModuleuserrelation record);
}