package deepthinking.fgi.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "算法参数动作")
public class TableAlgorithmcondition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.ID
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.AlgorithmRoleID
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "算法算子ID")
    private Integer algorithmroleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.FuncID
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "算法参数ID")
    private Integer funcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.Behavior
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "行为")
    private String behavior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.ValueSources
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "值来源")
    private Long valuesources;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.expression
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "表达式")
    private String expression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.Remark
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "备注")
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.ID
     *
     * @return the value of table_algorithmcondition.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.ID
     *
     * @param id the value for table_algorithmcondition.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.AlgorithmRoleID
     *
     * @return the value of table_algorithmcondition.AlgorithmRoleID
     *
     * @mbg.generated
     */
    public Integer getAlgorithmroleid() {
        return algorithmroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.AlgorithmRoleID
     *
     * @param algorithmroleid the value for table_algorithmcondition.AlgorithmRoleID
     *
     * @mbg.generated
     */
    public void setAlgorithmroleid(Integer algorithmroleid) {
        this.algorithmroleid = algorithmroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.FuncID
     *
     * @return the value of table_algorithmcondition.FuncID
     *
     * @mbg.generated
     */
    public Integer getFuncid() {
        return funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.FuncID
     *
     * @param funcid the value for table_algorithmcondition.FuncID
     *
     * @mbg.generated
     */
    public void setFuncid(Integer funcid) {
        this.funcid = funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.Behavior
     *
     * @return the value of table_algorithmcondition.Behavior
     *
     * @mbg.generated
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.Behavior
     *
     * @param behavior the value for table_algorithmcondition.Behavior
     *
     * @mbg.generated
     */
    public void setBehavior(String behavior) {
        this.behavior = behavior == null ? null : behavior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.ValueSources
     *
     * @return the value of table_algorithmcondition.ValueSources
     *
     * @mbg.generated
     */
    public Long getValuesources() {
        return valuesources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.ValueSources
     *
     * @param valuesources the value for table_algorithmcondition.ValueSources
     *
     * @mbg.generated
     */
    public void setValuesources(Long valuesources) {
        this.valuesources = valuesources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.expression
     *
     * @return the value of table_algorithmcondition.expression
     *
     * @mbg.generated
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.expression
     *
     * @param expression the value for table_algorithmcondition.expression
     *
     * @mbg.generated
     */
    public void setExpression(String expression) {
        this.expression = expression == null ? null : expression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.Remark
     *
     * @return the value of table_algorithmcondition.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.Remark
     *
     * @param remark the value for table_algorithmcondition.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}