package deepthinking.fgi.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "算法参数动作")
public class TableAlgorithmcondition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.ID
     *
     * @mbg.generated
     */
     @ApiModelProperty(value = "ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.InterfaceRoleID
     *
     * @mbg.generated
     */
      @ApiModelProperty(value = "算法算子ID")
    private Integer interfaceroleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.InterfaceParametersID
     *
     * @mbg.generated
     */
     @ApiModelProperty(value = "算法参数ID")
    private String interfaceparametersid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.Behavior
     *
     * @mbg.generated
     */
     @ApiModelProperty(value = "行为")
    private String behavior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.ValueSources
     *
     * @mbg.generated
     */
      @ApiModelProperty(value = "条件值来源（输入或者输出的ID）")
    private Integer valuesources;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.expression
     *
     * @mbg.generated
     */
     @ApiModelProperty(value = "表达式")
    private String expression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcondition.Remark
     *
     * @mbg.generated
     */
     @ApiModelProperty(value = "备注")
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.ID
     *
     * @return the value of table_algorithmcondition.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.ID
     *
     * @param id the value for table_algorithmcondition.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.InterfaceRoleID
     *
     * @return the value of table_algorithmcondition.InterfaceRoleID
     *
     * @mbg.generated
     */
    public Integer getInterfaceroleid() {
        return interfaceroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.InterfaceRoleID
     *
     * @param interfaceroleid the value for table_algorithmcondition.InterfaceRoleID
     *
     * @mbg.generated
     */
    public void setInterfaceroleid(Integer interfaceroleid) {
        this.interfaceroleid = interfaceroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.InterfaceParametersID
     *
     * @return the value of table_algorithmcondition.InterfaceParametersID
     *
     * @mbg.generated
     */
    public String getInterfaceparametersid() {
        return interfaceparametersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.InterfaceParametersID
     *
     * @param interfaceparametersid the value for table_algorithmcondition.InterfaceParametersID
     *
     * @mbg.generated
     */
    public void setInterfaceparametersid(String interfaceparametersid) {
        this.interfaceparametersid = interfaceparametersid == null ? null : interfaceparametersid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.Behavior
     *
     * @return the value of table_algorithmcondition.Behavior
     *
     * @mbg.generated
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.Behavior
     *
     * @param behavior the value for table_algorithmcondition.Behavior
     *
     * @mbg.generated
     */
    public void setBehavior(String behavior) {
        this.behavior = behavior == null ? null : behavior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.ValueSources
     *
     * @return the value of table_algorithmcondition.ValueSources
     *
     * @mbg.generated
     */
    public Integer getValuesources() {
        return valuesources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.ValueSources
     *
     * @param valuesources the value for table_algorithmcondition.ValueSources
     *
     * @mbg.generated
     */
    public void setValuesources(Integer valuesources) {
        this.valuesources = valuesources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.expression
     *
     * @return the value of table_algorithmcondition.expression
     *
     * @mbg.generated
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.expression
     *
     * @param expression the value for table_algorithmcondition.expression
     *
     * @mbg.generated
     */
    public void setExpression(String expression) {
        this.expression = expression == null ? null : expression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcondition.Remark
     *
     * @return the value of table_algorithmcondition.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcondition.Remark
     *
     * @param remark the value for table_algorithmcondition.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}