package deepthinking.fgi.domain;

public class TableAlgorithmcoordinate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcoordinate.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcoordinate.RoleId
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_algorithmcoordinate.CoordinateInfo
     *
     * @mbg.generated
     */
    private byte[] coordinateinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcoordinate.id
     *
     * @return the value of table_algorithmcoordinate.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcoordinate.id
     *
     * @param id the value for table_algorithmcoordinate.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcoordinate.RoleId
     *
     * @return the value of table_algorithmcoordinate.RoleId
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcoordinate.RoleId
     *
     * @param roleid the value for table_algorithmcoordinate.RoleId
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_algorithmcoordinate.CoordinateInfo
     *
     * @return the value of table_algorithmcoordinate.CoordinateInfo
     *
     * @mbg.generated
     */
    public byte[] getCoordinateinfo() {
        return coordinateinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_algorithmcoordinate.CoordinateInfo
     *
     * @param coordinateinfo the value for table_algorithmcoordinate.CoordinateInfo
     *
     * @mbg.generated
     */
    public void setCoordinateinfo(byte[] coordinateinfo) {
        this.coordinateinfo = coordinateinfo;
    }

    public TableAlgorithmcoordinate(Integer roleid, byte[] coordinateinfo) {
        this.roleid = roleid;
        this.coordinateinfo = coordinateinfo;
    }

    public TableAlgorithmcoordinate() {
    }
}