package deepthinking.fgi.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "算子接口参数信息")
public class TableInterfaceparameters {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_interfaceparameters.ID
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_interfaceparameters.InterfaceID
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "接口ID")
    private Integer interfaceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_interfaceparameters.ParametersSources
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "参数来源 算子的参数ID或者常量")
    private String parameterssources;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_interfaceparameters.ID
     *
     * @return the value of table_interfaceparameters.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_interfaceparameters.ID
     *
     * @param id the value for table_interfaceparameters.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_interfaceparameters.InterfaceID
     *
     * @return the value of table_interfaceparameters.InterfaceID
     *
     * @mbg.generated
     */
    public Integer getInterfaceid() {
        return interfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_interfaceparameters.InterfaceID
     *
     * @param interfaceid the value for table_interfaceparameters.InterfaceID
     *
     * @mbg.generated
     */
    public void setInterfaceid(Integer interfaceid) {
        this.interfaceid = interfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_interfaceparameters.ParametersSources
     *
     * @return the value of table_interfaceparameters.ParametersSources
     *
     * @mbg.generated
     */
    public String getParameterssources() {
        return parameterssources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_interfaceparameters.ParametersSources
     *
     * @param parameterssources the value for table_interfaceparameters.ParametersSources
     *
     * @mbg.generated
     */
    public void setParameterssources(String parameterssources) {
        this.parameterssources = parameterssources == null ? null : parameterssources.trim();
    }
}