package deepthinking.fgi.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "算法参数信息")
public class TableFunc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_func.ID
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_func.AlgorithmID
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "算子ID")
    private Integer algorithmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_func.VarName
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "参数名称")
    private String varname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_func.VarType
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "变量类型：基本类型、对象、常量")
    private String vartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_func.ValValue
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "变量值： 变量类型为常量时，此处为具体数值;类型为对象时，此处为模型名称或者ID;类型为基本类型时，此处为基本类型名称")
    private String valvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_func.InOrOut
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "是输入参数还是输出结果 0表输入，1表输出结果")
    private Long inorout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_func.Remark
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "备注")
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_func.ID
     *
     * @return the value of table_func.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_func.ID
     *
     * @param id the value for table_func.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_func.AlgorithmID
     *
     * @return the value of table_func.AlgorithmID
     *
     * @mbg.generated
     */
    public Integer getAlgorithmid() {
        return algorithmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_func.AlgorithmID
     *
     * @param algorithmid the value for table_func.AlgorithmID
     *
     * @mbg.generated
     */
    public void setAlgorithmid(Integer algorithmid) {
        this.algorithmid = algorithmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_func.VarName
     *
     * @return the value of table_func.VarName
     *
     * @mbg.generated
     */
    public String getVarname() {
        return varname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_func.VarName
     *
     * @param varname the value for table_func.VarName
     *
     * @mbg.generated
     */
    public void setVarname(String varname) {
        this.varname = varname == null ? null : varname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_func.VarType
     *
     * @return the value of table_func.VarType
     *
     * @mbg.generated
     */
    public String getVartype() {
        return vartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_func.VarType
     *
     * @param vartype the value for table_func.VarType
     *
     * @mbg.generated
     */
    public void setVartype(String vartype) {
        this.vartype = vartype == null ? null : vartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_func.ValValue
     *
     * @return the value of table_func.ValValue
     *
     * @mbg.generated
     */
    public String getValvalue() {
        return valvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_func.ValValue
     *
     * @param valvalue the value for table_func.ValValue
     *
     * @mbg.generated
     */
    public void setValvalue(String valvalue) {
        this.valvalue = valvalue == null ? null : valvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_func.InOrOut
     *
     * @return the value of table_func.InOrOut
     *
     * @mbg.generated
     */
    public Long getInorout() {
        return inorout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_func.InOrOut
     *
     * @param inorout the value for table_func.InOrOut
     *
     * @mbg.generated
     */
    public void setInorout(Long inorout) {
        this.inorout = inorout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_func.Remark
     *
     * @return the value of table_func.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_func.Remark
     *
     * @param remark the value for table_func.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}